name: Scheduled Notification

on:
  schedule:
    - cron: '40 * * * *'

  workflow_dispatch:    # Allow manual runs too

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Vercel Endpoint
        run: |
          curl -X GET https://med-schedule-theta.vercel.app/api/sendNotifications
