name: Scheduled API Call

on:
  schedule:
    # Runs every day at 7:00 AM UTC
    - cron: '35 * * * *'

jobs:
  call_api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API Endpoint
        run: |
          curl -X POST https://med-schedule-theta.vercel.app/api/sendNotifications -H "Authorization: Bearer YOUR_TOKEN" -H "Content-Type: application/json" -d '{"key":"value"}'
